config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  devise_for :users

  root "home#index"

  get 'dashboard' => 'home#dashboard', as: 'dashboard'

  resources :posts
  resources :categories, only: [:index, :show]
  resources :tags, only: [:index, :show]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/categorized_posting.rb
class CategorizedPosting < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  # fix this association
  belongs_to :category
  belongs_to :author, class_name: "User", foreign_key: "author_id"
  belongs_to :category
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_attached_file :image, styles: { x_large: "1200x800", small: "400x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  # scope :ordered, :order => "created_at DESC"

  def self.published
    Post.where(is_published: true).order("created_at DESC")
  end

  def self.unpublished
    Post.where(is_published: false)
  end

  def content_limited
    words = self.content.split
    if words.length < 50
      return self.content
    else
      words[0..50].join(' ') + "..."
    end       
  end

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
        Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end

  def status
    if self.is_published == true
      return "Published"
    else
      return "Submitted on #{self.created_at.strftime("%B %d, %Y")}"
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, :foreign_key => 'author_id'
  has_attached_file :avatar, styles: { medium: "200x200>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |user_params|
      user_params.permit(:first_name, :last_name, :email, :password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @featured
    @published = Post.where(is_published: true).order("created_at DESC")
  end

  def dashboard
    @user_posts = current_user.posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :get_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.paginate(:page => params[:page], per_page: 6)
    @published = Post.where(is_published: true)
  end

  def search
    title = params[:title]
    student = Post.find_by(title)
    if(post != nil)
      redirect_to post
    else
      @error = "The post was not found"
      render "posts/index"
    end
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: "Post was successfully created"
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated"
    else
      render "edit"
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post was deleted"
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :image, :all_tags)
  end

  def get_post
    @post = Post.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :get_tag, only: [:show]
  def index 
  end

  def show
    @posts = Post.tagged_with(@tag.name)   
  end

  private

  def get_tag
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if user_signed_in?
      @posts = Post.published + Post.unpublished.where(user_id: current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def featured_post_image
    featured_post = Post.where(is_featured: true)[0]
    featured_post.image
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ")
  end

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.haml
.container
  - @categories.each do |category|
    .index-wrapper
      %strong.post-title
        = link_to category.name, category

app/views/home/dashboard.html.haml
.container
  .row
    .col.s12.m3
      %aside.sidebar
        %i.material-icons.small settings
        = link_to "Account Settings", edit_user_registration_path
        %br
        %i.material-icons.small mode_edit
        = link_to "New Post", new_post_path
    .col.s12.m9
      - @user_posts.each do |post|
        .dashboard-post.z-depth-1
          .row
            .col.s2.m1.check
              - if post.is_published
                %i.material-icons.small.i-green check_circle
              - else
                %i.material-icons.small.i-yellow check_circle
            .col.s10.m11
              %h5= post.title
              %p
              = post.status
              &nbsp;|&nbsp;
              = link_to "Edit", edit_post_path(post)
              &nbsp;|&nbsp;
              = link_to "Delete"

app/views/home/index.html.haml
-# .row
-#   .col.s12.m6.featured-post
-#     = image_tag(featured_post_image)
-#   .col.s12.m6.featured-page
-#     = image_tag(featured_post_image)
-#     .row
-#       .col.s6.m3.small-featured
-#         = image_tag(featured_post_image)
-#       .col.s6.m3.small-featured
-#         = image_tag(featured_post_image)
.container
  - @published.each do |post|
    .row
      .col.s12.m4.l3.post-image-small.valign-wrapper
        = image_tag(post.image.url(:medium), class: "valign")
      .col.s12.m8.l9.post
        %h2
          = link_to post.title, post
        -# = post.created_at.strftime("%B %d, %Y")
        %p
          .strong
            = time_ago_in_words(post.created_at)
            ago
        %p
          = truncate(post.content, length: 200)
          = link_to "Read More", post

app/views/layouts/application.html.haml
!!! HTML
%html
  %head
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    "https://fonts.googleapis.com/icon?family=Material+Icons"
    = stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Fredoka+One'

    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav
      .nav-wrapper

        =link_to "DevReboot", root_path, id: "site-title"
        =link_to "#", :data => { :"data-activates" => "mobile-demo" }, class: "button-collapse" do
          %i.material-icons menu
        end
        %ul.right.hide-on-med-and-down
          - if user_signed_in?
            %li
              = link_to "New Post", new_post_path
            %li
              = link_to "Dashboard", dashboard_path
            %li
              = link_to "Logout", destroy_user_session_path, { method: :delete }
          -else
            %li
              =link_to "Login", new_user_session_path
            %li
              =link_to "Register", new_user_registration_path
          %li
            =link_to "Contributors"
          %li
            =link_to "Categories", categories_path
        %ul.side-nav#mobile-demo
          - if user_signed_in?
            %li
              = link_to "New Post", new_post_path
            %li
              = link_to "Dashboard"
          -else
            %li
              =link_to "Login", new_user_session_path
            %li
              =link_to "Register", new_user_registration_path
          %li
            =link_to "About"
          %li
            =link_to "Contributors"
          %li
            =link_to "Categories", categories_path
    .container
      %p.notice
        = notice
      %p.alert
        = alert
    =yield
    .container
      %footer Copyright &copy; 2016 Becca, Farman, and Max | All Rights Reserved
  -#
  -# #login.modal
  -#   .modal-content
  -#     = render "devise/sessions/form"

app/views/posts/_form.html.haml
= form_for @post do |f|
  .input-field
    = f.text_field :title, placeholder: "Title"
  .input-field
    = f.text_area :content, class: "materialize-textarea"
    = f.label :content
  .input-field
    = f.text_field :all_tags, placeholder: "Tags separated with comma"
  .file-field.input-field
    .btn
      Choose File
      = f.file_field :image
    .file-path-wrapper
      %input.file-path.validate
  .input-field
    = raw tag_links(@post.all_tags)
  .waves-effect.waves-light.btn
    = f.submit

app/views/posts/edit.html.haml
.container
  %h1 Edit Post
  = render "form"

app/views/posts/index.html.haml
.container
  %h1.posts-header Posts
  - @posts.each do |post|
    .index-wrapper
      %strong.post-title
        = link_to post.title, post
      .post-date
        Posted 
        = time_ago_in_words(post.created_at) 
        ago by 
        = post.author.full_name
      = post.content_limited
  = will_paginate @posts, renderer: MaterializePagination::Rails

app/views/posts/new.html.haml
.container
  %h1 Create a new post
  = render "form" 

app/views/posts/show.html.haml
.post-image.center-align
  = image_tag @post.image.url(:x_large)
.container.post-show
  %h1.posts-header
    = @post.title
  %p.post-details
    %strong
      Posted by: 
      = @post.author.full_name
      %br
      on 
      = @post.created_at.strftime("%B %d, %Y")
  %p.post-content
    = @post.content
  %p
    Tags:
    - @post.tags.each do |tag|
      .chip
        = link_to "#{tag.name}", tag_path
  - if @post.author == current_user
    %p
      %strong
        Status:
      = @post.status
    = link_to "Edit", edit_post_path(@post)
    = link_to "Delete", @post, data: {confirm: "Are you sure you want to delete this post?"}, method: :delete
  = link_to "Back", posts_path

app/views/tags/show.html.haml
.container
  %h3
    Posts tagged as 
    = @tag.name
  - @posts.each do |post|
    .index-wrapper
      %strong.post-title
        = link_to post.title, post
      .post-date
        Posted 
        = time_ago_in_words(post.created_at) 
        ago by 
        = post.author.full_name
      = post.content_limited
   